POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hc28iLCJpZCI6IjYyY2Q2YzNlNGQ3ZjQ1MzI3Y2IwMTc5MyIsImlhdCI6MTY1NzYyOTc5MSwiZXhwIjoxNjU3NjMzMzkxfQ.mVUuPnGiXmcm5SsmD4BDuZ-7TkkLwRIkef8DLl2QaFk

{
    "title": "nyt on blogssssssssssskliiie",
    "author": "jaakkojoku",
    "url": "jotaintanne",
    "likes": 4
}